### ISSUE TITLE
Proposal to use different tag scheme

### ISSUE THREAD

**Issue by zallarak** [jcalazan/ansible-django-stack#12]
Using this current scheme:

```
- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: '{{ application_path }}'
    virtualenv: '{{ virtualenv_path }}'
    settings: '{{ django_settings_file }}'
  environment: django_environment
  when: run_django_syncdb
  tags: django

- name: Run Django South migrations
  django_manage:
    command: migrate
    app_path: '{{ application_path }}'
    virtualenv: '{{ virtualenv_path }}'
    settings: '{{ django_settings_file }}'
  environment: django_environment
  when: run_django_south_migration
  tags: django

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: '{{ application_path }}'
    virtualenv: '{{ virtualenv_path }}'
    settings: '{{ django_settings_file }}'
  environment: django_environment
  when: run_django_collectstatic
  tags: django
```

Is there any way one could run just one of these tasks from the command line? The following command runs all tasks with true values for the when clause as determined by the environment:

`$ ansible-playbook development.yml --tags "django"`

For example, it would be nice to migrate the app without running django's syncdb:

`$ ansible-playbook development.yml --tags "django_migrate"`

If I'm missing a way to do this without modifying the tags, please let me know. I can see the logic of being able to group tasks.. I just want to conditionally run it via the command line, and was hoping there was a way around verbosely supplying lots of variable overrides as migrations are much more common than syncdb, etc.
