### ISSUE TITLE
Problem with gunicorn/directory names/importerror

### ISSUE THREAD

**Issue by ghost** [jcalazan/ansible-django-stack#20]
http://dpaste.com/3354G9X

This, essentially.

I'm concerned that I don't understand the names (project_name, application_name) and that somehow I'm creating a conflict there.

Provisioning always errors on the Restart Supervisor task.

http://dpaste.com/2M6BD66

Any help? What else can I provide? My repository is here:
https://github.com/mekhami/npdhub 

That includes my modified provisioning playbooks.

**Comment by jcalazan** [comment]
Hey Nekham,

`project_name` is basically the Git project root directory, the application name is the Django main app (which, in many cases, are probably the same).  The main thing to watch out for is the location of the `wsgi.py` file.

For example, in here: https://github.com/jcalazan/youtube-audio-dl/blob/master/ansible/roles/web/templates/gunicorn_start.j2

If the `wsgi.py` file is in `myproj/myproj/wsgi.py`, then `$DJANGODIR` value should be `myproj/`, as gunicorn looks for `myproj.wsgi`.

**Comment by mekhami** [comment]
@jcalazan I think the problem I'm encountering is the project_name and application_name variables in roles/web/vars/main.yml. 

What are these 'supposed' to be and is it a problem if they are the same thing?

**Comment by jcalazan** [comment]
@mekhami It shouldn't be a problem if they're the same thing, but if your project structure is different from the example in the README, then it will cause problems.  According to the error, it couldn't find the `manage.py` file.  In your case, the manage.py file is one more level deep.

I think you'll just need to change this:

 ```
- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}" -> change this to "{{ project_path }}/{{ application_name }}" (basically ndphub/ndphub as the manage.py file is in this directory)
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate
```
