### ISSUE TITLE
Postgres error when provisioning

### ISSUE THREAD

**Issue by alfonsoperez** [jcalazan/ansible-django-stack#23]
Hi there,

Has someone encountered this error while provisioning?:

On the task:

    - name: Ensure database is created
      sudo_user: postgres
      postgresql_db: name={{ db_name }}
                     encoding='UTF-8'
                     lc_collate='en_US.UTF-8'
                     lc_ctype='en_US.UTF-8'
                     template='template0'
                     state=present

> Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql>/.s.PGSQL.5432"

While doing some tests on the local machine I was able to overcome this temporarly by logging in, doing `apt-get remove --purge postgres` and then installing `postgres-9.1`  in the task **Install PostgreSQL**, notice the version instead.

However this is not reliable, Have you guys encountered this error?

Cheers!

**Comment by AlfonsoPerez** [comment]
I got it working adding some tasks:
In roles/base/tasks/main.yml I added

    - name: Install Language packages
      apt: name=language-pack-en update_cache={{ update_apt_cache}} force=yes state=latest
      tags: packages

And in roles/db/tasks/main.yml I added:

    - name: Set Locale
      lineinfile: dest=/etc/environment
                  line="LC_ALL=\"en_US.UTF-8\""
                  state=present

    - name: Create PostgreSQL cluster
      command: pg_createcluster 9.3 main --start
      sudo: yes

What do you think? Cheers

**Comment by jcalazan** [comment]
Hmm...haven't seen this before.  What version of Ubuntu are you running?

**Comment by AlfonsoPerez** [comment]
It happened to me both on 'ubuntu/precise64' and 'ubuntu/trusty64'

**Comment by jcalazan** [comment]
Weird, I'm on precise64 as well, I'm guessing something changed with the latest version.  Will test this out later and probably pin the version as well as you mentioned.  Thanks for taking a look into this!

**Comment by AlfonsoPerez** [comment]
My problem was finally *I think* that LC_ALL was unset so pg_createcluster was complaining, but doing apt-get install language-pack-en solves it, but still haven't had the time to deep more into the issue, really loving your stack, has made me the life much easier learning ansible.

**Comment by alfetopito** [comment]
Hey there.

I'm having the same issue, on ubuntu/trusty64.

Have tried the suggestions by @AlfonsoPerez , and even added couple of locale-gen. I had locale issues before, and as far as I remember, doing a locale-gen was usually enough to fix it:

```
- name: Install Language packages
  apt: name=language-pack-en update_cache={{ update_apt_cache}} force=yes state=latest
  tags: packages

- name: Locale (is a b****)
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US  
    - en_US.UTF-8 
    - pt_BR.UTF-8
    - de_DE.UTF-8

- name: Install PostgreSQL
...
```

But no luck so far.

Any ideas on where to go from here?


Oh and yes, this stack is awesome @jcalazan , tks for your time putting it together :)
