### ISSUE TITLE
Envirponmental variables are not set after creating postactivate file

### ISSUE THREAD

**Issue by AmirMeirbekov** [jcalazan/ansible-django-stack#39]
Hello

Playbook runs without errors and creates postactivate file, but it doesn't actually export environmental variables. I notice this when I try to create superuser manually and always get a error that it can't connect to database because no credentials supplied.

Task for postactivate
``` 
- name: Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  tags: deploy
```
Environmental variables
```
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_pass }}"
```

Database settings
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        # 'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}
```

How can I ensure that django variables exported?
