### ISSUE TITLE
django makemigrations permissions denied

### ISSUE THREAD

**Issue by codegastudio** [jcalazan/ansible-django-stack#55]
Hello,

Impossible to deploy my models with migrate command.

application_name
|- manage.py
|- project
|--- settings.py
|--- models
|----- **init**.py
|----- object1.py
|----- object2.py

```
- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
  environment:
    PATH: "{{ virtualenv_path }}/bin:{{ lookup('env', 'PATH') }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate
```

Same problem when i want migrate directly on the server.
After activate virtualenv, i try `./manage.py makemigrations project` and get Permission denied error message to create migrations repository.

I have tried to change permissions on all files but nothing change.
Finally i have success to process makemigrations command like that
`sudo /virtualenv_path/bin/python ./manage.py makemigrations project`
But this not the goal to do this like that.

Any help will be appreciated.
Regards

pip freeze inside the virtualenv :
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.23
celery==3.1.23
Django==1.9.8
django-push-notifications==1.4.1
djangorestframework==3.4.0
djoser==0.5.0
gunicorn==19.6.0
kombu==3.0.35
psycopg2==2.6.2
pytz==2016.6.1
Unidecode==0.4.19

**Comment by jcalazan** [comment]
@codegastudio What are the permissions of the `manage.py`file?

**Comment by codegastudio** [comment]
@jcalazan permissions were not set at the moment of migrate command is call so manage.py is :
`-rwxr-xr-x 1 root root  250 Jul 19 18:42 manage.py`

**Comment by jcalazan** [comment]
Hmm...permissions looks right, I remember seeing a similar error before the issue was the manage.py file wasn't excutable in the git repo.

Mind pasting the error from Ansible? You can add `-vvvv` flag to the `ansible-playbook` command to get more detailed info from Ansible.

**Comment by codegastudio** [comment]
Hi,

I changed few steps in setup_django_app.
Django 1.9 no longer use syncdb method.
We need to call makemigrations command with project name (eg:project in my case) before call migrate command.

So i tested the followed ansible instructions and this work

```
- name: Run Django database makemigrations
  django_manage: >
    command="makemigrations project"
    app_path={{ project_path }}
    virtualenv={{ virtualenv_path }}
    settings={{ django_settings_file }}
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django database migrate
  django_manage: >
    command=migrate 
    app_path={{ project_path }}
    virtualenv={{ virtualenv_path }}
    settings={{ django_settings_file }}
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate
```

**Comment by codegastudio** [comment]
Just add "migrations" repository in your django project and you will not be oblige to call makemigrations followed by your project name

```
- name: Run Django database makemigrations
  django_manage: >
    command=makemigrations
    app_path={{ project_path }}
    virtualenv={{ virtualenv_path }}
    settings={{ django_settings_file }}
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate
```

**Comment by jcalazan** [comment]
Glad you got it working @codegastudio, I believe the `startapp` command starting from Django 1.8 automatically creates the `migrations` directory/package.

**Comment by codegastudio** [comment]
@jcalazan yes it's from Django 1.8 👍

**Comment by mprat** [comment]
It looks like a bug with the django_manage Ansible add-on. I solved it by making the manage.py file executable after I clone my repository.

```
- name: Make manage.py executable
  file:
    path: "{{ project_path }}/manage.py"
    mode: 0777
```

Not a long-term solution, I know, but it will solve the problem.
